language: node_js
node_js:
- '7.5'
script:
  - hexo generate
deploy:
  provider: s3
  secret_access_key:
    secure: lhZcKuWhCmfmMtFrSGUh65R/DPnfQV9YECq/0gI8Zg450P8ES8qT+R7naI8llL964aWOroc67oSCEHQv44mnUjRihmhEVvSSvV5OTPscqphDC8K+Fwj0EqqLwyTeV4upTQvhcfeADxjq0dCdAkpCMebie0rzYqyaPnkpz2tZNpb6eCywq58n3ygZHz6dv8pNEfFSSh163wM281rGBAYEB03w6aUgfHa9VWolV9q61z0FUvtCq97PuVF+wLeutCn+YTVY9GxjyVed1xN7r3Nu2fkul7xqgmiJ1WZsMV7uv4gkdnKwPMsT3nbHMkoeQcFjUnG5B0oz9vzLehJK1ksqGE8u8XqdfKBhfJszjvXckIchidDvgD7tcJB7lWO3PcVbuGka74AZ9+pEa6jXfmzpwAQef7UfOcf0nkapHLcePF4z4/EfRcZVgpwSv2dJTXa+S7HbPtorfatyLBoI2mAwqHN5UTZlS9MNtwT96ibw+T9hd++HVmtBSgkM9HLDoStKz1N+6/7q7t/hcgDrmB1plpWJqv711ehEi9TKcwtl+Y6JWA2U0rDCrPPkoWqRo3Dz9G1lnMJxGGBmFgKYbjuIzDXONqS6H5zYG/S+I6h07RkTiqa3An5TpPmVVPjqp1bKfXd5cPO6yKXxiuNvpyxogO8ABFGB3LVmCNsTR3ocMNY=
  access_key_id:
    secure: Ub1FR8vjB26T+rsVfwGwan3E2R8FDAsbOm86cR0ETmVeaIB2BX/2vBB83qHDbTFCNfXoG4jY60VAM65DgUNZVpvY47twADYsC8jbCnOWJ+GX54pETNvFhC6gzKuWHHffO1k8F2Yowm7QI1xu4A8ZURWrlx7kRzwU5067iv4yrppgDcIGOF5Nj7AykfuGWnGtRc54MacBd3AmcmUh6PRS6SAYD3loMNI0413cQYaI3pgN+EGccnyhz4N4C/+o8g2XclbIcZdjDEqbeEgDiJzybsp3lO0h4lw5iQT46h6VlTbxlEtAp47Jfn/O7EUjeEEniEQBzGQQke1qBws31A8WbtPNvfNq1qqxyycSjW/qgTjlziDbnm/e3sOvRIrhz4mfcWC6RVp0o6Bx8Ylyc4DDKrzL6HPG2Uoh4lCH4DsMCUCckcVBrsVK17EiLMS3y5p6whL8MwHaM/CS4F2GEgRXFksWqYlyE4OprQz6u5uOjXvoU30orUp71jL+U0Pumf8uUWo9HeW3ygLa1zgUt6LR8KwsI4I2w3H/F20oofPRyJ7aoMU7ROLTyEgWoxxhSYkNsO5wZNbKNO2YHikLm8nLLqVXv+eCs4FiJUBs1rUcXHhti5XhspNJFEVfGikD2zySqVvtdQwvHxE0i2oW+WRjewrAIIKZre6hrLbcm3pkZ9M=
  bucket: elzbieta.niesmigielska.com
  skip_cleanup: true
  region: eu-central-1
  local_dir: public
  detect_encoding: true
  default_text_charset: 'utf-8'
  cache_control: "max-age=3600"
